services:
  tdx-api:
    build:
      context: ../..
      dockerfile: cmd/server/Dockerfile
    image: tdx-api-server:latest
    container_name: tdx-api-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      tdx-net:
        ipv4_address: 192.168.1.48

networks:
  tdx-net:
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
